---
- name: apache | install apache
  apt: pkg=apache2 state=latest

- name: apache | enable rewrite module
  shell: a2enmod rewrite
  notify: restart apache

- name: apache | copy default site
  template: src=files/apache/000-default.conf dest=/etc/apache2/sites-available/000-default.conf owner=root group=root force=yes
  notify: restart apache

- name: apache | copy new envvars
  copy: src=files/apache/envvars dest=/etc/apache2/envvars owner=root group=root force=yes
  notify: restart apache