---
- name: init | update apt
  apt: update_cache=yes

- name: init | make sure python-software-properties is installed
  apt: pkg=python-software-properties state=latest

- name: init | setting es_ES locale
  shell: locale-gen es_ES.UTF-8

- name: init | adding system packages
  apt: pkg={{ item }} state=latest
  with_items: sys_packages

- name: init | adding ppas
  apt_repository: repo={{ item }}
  with_items: apt_repositories

- name: init | update apt
  apt: update_cache=yes